host: api.cnbattle.com
info:
  contact: {}
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      parameters:
      - description: 用户Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      summary: 首页
swagger: "2.0"
